#!/bin/sh

DEVICE=$2
PARTED="parted -s -a opt"
PARTPROBE=partprobe
DIR=$1
ROOT_DIR=`mktemp -d /tmp/febmc.XXXXXX`
TYPE="install"

if [ $# -eq 3 ]; then
    if [ $3 == "-u" ]; then
        TYPE="update";
    fi
fi

if [ $TYPE == "install" ]; then
    $PARTED /dev/$DEVICE mktable msdos
    $PARTED /dev/$DEVICE mkpart primary -- 5 620.0
    $PARTED /dev/$DEVICE mkpart primary -- 620.0 2800.0
    $PARTED /dev/$DEVICE mkpart primary -- 2800.0 -2
    $PARTED /dev/$DEVICE set 1 boot on
    $PARTPROBE /dev/$DEVICE
fi

dd if=$DIR/boot.img of=/dev/${DEVICE}1 bs=1M
sync
e2fsck -f /dev/${DEVICE}1
resize2fs /dev/${DEVICE}1

dd if=$DIR/root.img of=/dev/${DEVICE}2 bs=1M
sync
e2fsck -f /dev/${DEVICE}2
resize2fs /dev/${DEVICE}2

if [ $TYPE == "install" ]; then
    dd if=$DIR/home.img of=/dev/${DEVICE}3 bs=1M
    sync
    e2fsck -f /dev/${DEVICE}3
    resize2fs /dev/${DEVICE}3
fi

mount /dev/${DEVICE}2 $ROOT_DIR
mount /dev/${DEVICE}1 $ROOT_DIR/boot
mount /dev/${DEVICE}3 $ROOT_DIR/home
mount -t proc proc $ROOT_DIR/proc
mount -t sysfs sys $ROOT_DIR/sys
mount -obind /dev $ROOT_DIR/dev
(
cd $ROOT_DIR
chroot $ROOT_DIR grub2-install /dev/${DEVICE}
chroot $ROOT_DIR grub2-mkconfig -o /boot/grub2/grub.cfg
)
sync

umount $ROOT_DIR/proc
umount $ROOT_DIR/sys
umount $ROOT_DIR/dev
sleep 2s
fuser -mv $ROOT_DIR/boot
fuser -mv $ROOT_DIR/home
umount $ROOT_DIR/boot
umount $ROOT_DIR/home
umount $ROOT_DIR
