#!/bin/sh

show_help()
{
   echo "Usage:"
   echo "-h        This useful help"
   echo "-u        Updates existing images (needs -i)"
   echo "-i dir    Directory with images"
   echo "-o dir    Directory where to put newly created images"
   exit 0
}

TYPE="create"

while getopts  "uo:i:h" i
do
    case "$i" in
        u) TYPE="update";;
        o) OUT_DIR=`realpath $OPTARG`;;
        i) DIR=`realpath $OPTARG`;;
        h) show_help; break;;
    esac
done


MKFS=mkfs.ext4
RUN_DIR=`pwd`

if [ $TYPE == "create" ]; then
    if [ -z $OUT_DIR ]; then
        echo "You must specify output directory!"
        exit 1;
    fi

    DIR=`mktemp -d /var/tmp/febmc.XXXXXX`
    mkdir $DIR
else
    if [ ! -d $DIR ]; then
        echo "Directory '$DIR' does not exists!";
        exit 1;
    fi
    if [ ! -f $DIR/root.img -o ! -f $DIR/boot.img ]; then
        echo "Images not found!";
        exit 1;
    fi
fi

ROOT_DIR=$DIR/root_install

if [ ! -d $ROOT_DIR ]; then
    mkdir $ROOT_DIR
fi

if [ $TYPE == "create" ]; then
    dd if=/dev/zero of=$DIR/root.img bs=1M count=0 seek=2048
fi
ROOT_LOOP=`losetup -f --show $DIR/root.img`
if [ $TYPE == "create" ]; then
    $MKFS $ROOT_LOOP -L rootfs
fi
mount $ROOT_LOOP $ROOT_DIR

yum -y --installroot=$ROOT_DIR -c $RUN_DIR/yum.conf install filesystem

if [ $TYPE == "create" ]; then
    dd if=/dev/zero of=$DIR/boot.img bs=1M count=0 seek=512
fi
BOOT_LOOP=`losetup -f --show $DIR/boot.img`
if [ $TYPE == "create" ]; then
    $MKFS $BOOT_LOOP -L bootfs
fi
mount $BOOT_LOOP $ROOT_DIR/boot

if [ $TYPE == "create" ]; then
    dd if=/dev/zero of=$DIR/home.img bs=1M count=0 seek=10
fi
HOME_LOOP=`losetup -f --show $DIR/home.img`
if [ $TYPE == "create" ]; then
    $MKFS $HOME_LOOP -L homefs
fi
mount $HOME_LOOP $ROOT_DIR/home

mount -t proc proc $ROOT_DIR/proc
mount -t sysfs sys $ROOT_DIR/sys
mount -obind /dev $ROOT_DIR/dev

echo "LABEL=\"rootfs\" /                   ext4    defaults        1 1" >  $ROOT_DIR/etc/fstab
echo "LABEL=\"bootfs\" /boot                   ext4    defaults        1 2" >>  $ROOT_DIR/etc/fstab
echo "LABEL=\"homefs\" /home                   ext4    defaults        1 2" >>  $ROOT_DIR/etc/fstab

yum -y --installroot=$ROOT_DIR -c $RUN_DIR/yum.conf install generic-logos generic-release generic-release-notes rpm grub2 binutils yum rpmfusion-free-release rpmfusion-nonfree-release
echo -e "GRUB_CMDLINE_LINUX=\"nomodeset\"\nGRUB_GFXPAYLOAD_LINUX=\"text\"" > $ROOT_DIR/etc/default/grub
echo "NETWORKING=yes" > $ROOT_DIR/etc/sysconfig/network

yum -y --installroot=$ROOT_DIR -c $RUN_DIR/yum.conf install alsa-utils libmad nfs-utils chrony openssh-server v4l-utils b43-openfwwf upower NetworkManager net-tools vim-minimal passwd e2fsprogs mc vim kernel xbmc xorg-x11-xinit xorg-x11-server-Xorg xorg-x11-drivers polkit rsyslog cronie cronie-anacron dbus-x11 mesa-dri-drivers

cp -f $RUN_DIR/files/xbmc.service $ROOT_DIR/etc/systemd/system
cp -f $RUN_DIR/files/80-xbmc.rules $ROOT_DIR/etc/polkit-1/rules.d
cp -f $ROOT_DIR/usr/share/X11/xorg.conf.d/50-synaptics.conf $RUN_DIR/files
patch $RUN_DIR/files/50-synaptics.conf < $RUN_DIR/files/50-synaptics.conf.patch
cp -f $RUN_DIR/files/50-synaptics.conf $ROOT_DIR/etc/X11/xorg.conf.d
install -D -m 644 -o root $RUN_DIR/files/remote.ir_keytable $ROOT_DIR/usr/local/share/ir_keytables/remote.ir_keytable
install -m 644 -o root $RUN_DIR/files/ir_keytable.service $ROOT_DIR/etc/systemd/system/ir_keytable.service

# media directories - no music videos yet
BASE_MEDIA_DIR=/home/media
MEDIA_DIRS=($BASE_MEDIA_DIR $BASE_MEDIA_DIR/local $BASE_MEDIA_DIR/local/movies $BASE_MEDIA_DIR/local/music $BASE_MEDIA_DIR/local/series $BASE_MEDIA_DIR/local/photos $BASE_MEDIA_DIR/network
$BASE_MEDIA_DIR/network/movies $BASE_MEDIA_DIR/network/music $BASE_MEDIA_DIR/network/series $BASE_MEDIA_DIR/network/photos)
for i in ${MEDIA_DIRS[*]}; do
    [ -d $ROOT_DIR/$i ] || mkdir $ROOT_DIR/$i;
done

. ./media_network_dirs

echo "$MUSIC     ${MEDIA_DIRS[8]}              nfs    defaults,user,auto        0 0" >>  $ROOT_DIR/etc/fstab
echo "$SERIES    ${MEDIA_DIRS[9]}               nfs    defaults,user,auto        0 0" >>  $ROOT_DIR/etc/fstab
echo "$PHOTOS    ${MEDIA_DIRS[10]}               nfs    defaults,user,auto        0 0" >>  $ROOT_DIR/etc/fstab
echo "$MOVIES    ${MEDIA_DIRS[7]}               nfs    defaults,user,auto        0 0" >>  $ROOT_DIR/etc/fstab

(
cd $ROOT_DIR
chroot $ROOT_DIR sh -c 'echo -e "FeBMC\nFeBMC" | passwd root --stdin'
chroot $ROOT_DIR sh -c 'cp -f /etc/skel/{*,.*} /root/'
chroot $ROOT_DIR sh -c 'id feplayer ||  useradd -mUp febmc feplayer'
chroot $ROOT_DIR sh -c 'usermod -G audio,cdrom feplayer'
chroot $ROOT_DIR systemctl enable rsyslog.service
chroot $ROOT_DIR systemctl enable xbmc.service
chroot $ROOT_DIR systemctl enable crond.service
chroot $ROOT_DIR systemctl enable ir_keytable.service
chroot $ROOT_DIR sync
)
sync
umount $ROOT_DIR/proc
umount $ROOT_DIR/sys
umount $ROOT_DIR/dev
umount $ROOT_DIR/boot
umount $ROOT_DIR/home
umount $ROOT_DIR

losetup -D

if [ $TYPE == "create" ]; then
    mv $DIR/root.img $OUT_DIR
    mv $DIR/boot.img $OUT_DIR
    mv $DIR/home.img $OUT_DIR
fi
